# Generated by Django 3.0.3 on 2020-08-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_statistics',
            name='listings_value_dd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='daily_statistics',
            name='total_listings_dd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='totalmodel',
            name='total_listings',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='totalmodel',
            name='total_sqm',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='totalmodel',
            name='total_value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
