# Generated by Django 3.0.3 on 2021-05-15 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20210515_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtotalmodel',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newtotal', to='scraper.MarketModel'),
        ),
        migrations.AlterField(
            model_name='totalmodel',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total', to='scraper.MarketModel'),
        ),
    ]
