# Generated by Django 3.0.3 on 2020-08-22 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20200822_1321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Daily_statistics',
            new_name='DailyStatistic',
        ),
        migrations.RenameModel(
            old_name='Monthly_statistics',
            new_name='MonthlyStatistic',
        ),
    ]
