# Generated by Django 3.0.3 on 2020-08-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_auto_20200822_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystatistic',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
