# Generated by Django 3.0.3 on 2020-09-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_auto_20200822_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_complex', models.IntegerField(blank=True, null=True)),
                ('error_price_sqm', models.IntegerField(blank=True, null=True)),
                ('populated_count', models.IntegerField(blank=True, null=True)),
                ('ads_searched', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorListings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.URLField(max_length=500)),
                ('error_message', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
