# Generated by Django 3.0.3 on 2020-09-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_dailyscan_errorlistings'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='bilde',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housemodel',
            name='postnummer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='housemodel',
            unique_together={('prisantydning', 'adress')},
        ),
    ]
